"""empty message

Revision ID: 21063d510470
Revises: bf53a63ddefc
Create Date: 2024-07-23 08:11:44.617020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21063d510470'
down_revision = 'bf53a63ddefc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
